image: php:7.3

before_script:
# gnupg is needed for below apt-key add command.
- apt-get update && apt-get install -y gnupg
# Install composer, nodejs & yarn dependencies
- curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
- echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
- apt-get update && apt-get install -y wget git zip unzip nodejs yarn
- wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
- php -r "copy( 'https://getcomposer.org/installer', 'composer-setup.php' );"
- php -r "if ( hash_file( 'SHA384', 'composer-setup.php' ) === file_get_contents( 'installer.sig' ) ) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink( 'composer-setup.php' ); } echo PHP_EOL;"
- php composer-setup.php
- php -r "unlink( 'composer-setup.php' ); unlink( 'installer.sig' );"
- php composer.phar install
- yarn install

# Composer stores all downloaded packages in the vendor/ directory.
# Do not use the following if the vendor/ directory is committed to
# your git repository.
# Same with yarn and node_modules.
cache:
  paths:
  - vendor/
  - node_modules/

stages:
  - lint

lint:
  stage: lint
  script:
  - make lint
